### ISSUE TITLE
Munit Issue with IP filters

### ISSUE THREAD

**Issue by vikramuppala** [mulesoft/munit#108]
Hi,

Currently I am trying to do mock on IP filter in my mule flow. I am sucessfully able to mock the IP filter message processor but the flow is not excuting to next message processor. 

And also I tired with unmocking the ip filter and tested the flow from munit the flow is getting stopped at ip filter and returning "{Nullpayload}" as response.

Syntax used to mock is:
	whenMessageProcessor("filter-by-ip").ofNamespace("filters").thenReturn(muleMessageWithPayload("ip"));

Ip regex i have mentioned to accept any range of IP. for normal testing its working for me.

Can some one help me out here..

**Comment by damiansima** [comment]
Hi there I will close this issue for the moment as we consider that mocking filters is not really a the way to go.

We can revisit this in the future though.

Cheers!
