### ISSUE TITLE
Munit test runs fine in Studio but fails via Maven

### ISSUE THREAD

**Issue by singirp** [mulesoft/munit#147]
Hi,
I have a simple munit test for a SOAP flow to send a request and assert the response. While this test runs fine in Anypoint studio, it throws an error when using Maven.
```
<munit:test name="soap-test" description="soap test">
        <set-payload value="#[string:someXMLinput]" doc:name="set input"/>
        <flow-ref name="soap-flow" doc:name="flow-ref-soap"/>
        <munit:assert-not-null doc:name="Assert Not Null Payload"/>        
        <object-to-string-transformer doc:name="Object to String"/>
        <munit:assert-on-equals expected-ref="#[string:someXMLOutput]" value-ref="#[payload]" doc:name="Assert Equals"/>
    </munit:test>
```
********************************************************************************
Message               : There are two transformers that are an exact match for input: "class java.lang.String", output: "class java.io.InputStream". Transformers are: "_ObjectToInputStream(class org.mule.transformer.simple.ObjectToInputStream)" and "_ObjectToInputStream(class org.mule.transformer.simple.ObjectToInputStream)"
Code                  : MULE_ERROR-255
--------------------------------------------------------------------------------
Exception stack is:
1. There are two transformers that are an exact match for input: "class java.lang.String", output: "class java.io.InputStream". Transformers are: "_ObjectToInputStream(class org.mule.transformer.simple.ObjectToInputStream)" and "_ObjectToInputStream(class org.mule.transformer.simple.ObjectToInputStream)" (org.mule.api.registry.ResolverException)
  org.mule.transformer.graph.GraphTransformerResolver:61 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/registry/ResolverException.html)
--------------------------------------------------------------------------------

If I comment the object-to-string-transformer I do not see this error. Could you please provide some hints on how to resolve this?

**Comment by singirp** [comment]
Here is the sample code..
```
<munit:test name="soap-test" description="soap test">
        <set-payload value="#[string:someXMLinput]" doc:name="set input"/>
        <flow-ref name="soap-flow" doc:name="flow-ref-soap"/>
        <munit:assert-not-null doc:name="Assert Not Null Payload"/>        
        <object-to-string-transformer doc:name="Object to String"/>
        <munit:assert-on-equals expected-ref="#[string:someXMLOutput]" value-ref="#[payload]" doc:name="Assert Equals"/>
    </munit:test>
```

**Comment by damiansima** [comment]
Hi @singirp what Munit version are you using?

**Comment by singirp** [comment]
Hi @damiansima 
Thanks a lot, the tests ran fine with 3.5-M3-SNAPSHOT
