### ISSUE TITLE
OOM during maven build

### ISSUE THREAD

**Issue by rafiqinvenio** [mulesoft/munit#148]
Hi Fernando,

I see "java.lang.OutOfMemoryError: Java heap space (org.mule.api.lifecycle.InitialisationException)"
exception during maven build. This issue is only when the project has a simple test case using "3.5-M2" version of MUnit.

An environment MAVEN_OPTS with -Xms128m -Xmx2024m -XX:PermSize=128m -XX:MaxPermSize=2048m is defined (My system has 8GM of RAM though)

I have tried increasing heap memory during mave build as below  but still no luck.
mvn clean package -DMAVEN_OPTS=-XX:MaxPermSize=2048m

More details:

Windows OS: 64bit 
RAM: 8 GM 
Java version: 1.7
Munit version : 3.5-M2
XSD Size: 23,801  bytes
Mule License: made available under src/test/resources

I would request you to please address issue  this asap.

Many thanks,
Rafiq

**Comment by rafiqinvenio** [comment]
FYI, 
Error I see in the console

[ERROR] Failed to execute goal org.mule.munit.tools:munit-maven-plugin:3.5-M2:test (test) on project schema-val: Execution test of goal org.mule.munit.tools:munit-maven-plugin:3.5-M2:test failed: org.mule.api.config.ConfigurationException: Error creating bean with name 'test-schema-validation-filterFlow1': Cannot create inner bean '(inner bean)' of type [org.mule.routing.MessageFilter] while setting bean property 'messageProcessors' with key [2]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)': Cannot resolve reference to bean 'Schema_Validation' while setting bean property 'filter'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'Schema_Validation': Invocation of init method failed; nested exception is java.lang.OutOfMemoryError: Java heap space (org.mule.api.lifecycle.InitialisationException) -> [Help 1]

**Comment by damiansima** [comment]
Hi @rafiqinvenio, 

Worst case scenario you should have your MAVEN_OPTS env var set to:
```
MAVEN_OPTS='-Xmx1G -XX:MaxPermSize=512m'
```
On the other hand, I'm not quite sure you can set MAVEN_OPTS as a -D property from the command line. Take a look at these links on how to do that properly on windows:
* http://stackoverflow.com/questions/2819853/setting-java-heap-space-under-maven-2-on-windows
* https://cwiki.apache.org/confluence/display/MAVEN/OutOfMemoryError

Now the other exception seems a little bit weird.
Would you mind sharing your code with me if the other suggestion doesn't work?

Cheers!!!

**Comment by rafiqinvenio** [comment]
Thanks for the reply @damiansima 

Increasing the PermSize didn't helped me with the fix. 

But the below solution helped me !! 
  
Solution : Modifying XSD with  maxOccurs from “99999” to “unbounded” for all applicable elements.
