### ISSUE TITLE
Munit throwing exception while running via maven

### ISSUE THREAD

**Issue by reddikumar001** [mulesoft/munit#149]
Hi,
I have a simple munit test for flow which having the batch excecute and subflows. it throws an error when running through Maven.

I am getting the following exception while running the test:

********************************************************************************
Message               : More than one object of type class org.mule.registry.TypeBasedTransformerResolver registered but only one expected.
Code                  : MULE_ERROR--2
--------------------------------------------------------------------------------

Please help me to resolve this issue.

**Comment by reddikumar001** [comment]
Please find the stack trace of the issue:

********************************************************************************
Message               : More than one object of type class org.mule.registry.TypeBasedTransformerResolver registered but only one expected.
Code                  : MULE_ERROR--2
--------------------------------------------------------------------------------
Exception stack is:
1. More than one object of type class org.mule.registry.TypeBasedTransformerResolver registered but only one expected. (org.mule.api.registry.RegistrationException)
  org.mule.registry.AbstractRegistry:164 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/registry/RegistrationException.html)
--------------------------------------------------------------------------------
Root Exception stack trace:
org.mule.api.registry.RegistrationException: More than one object of type class org.mule.registry.TypeBasedTransformerResolver registered but only one expected.
	at org.mule.registry.AbstractRegistry.lookupObject(AbstractRegistry.java:164)
	at org.mule.registry.AbstractRegistryBroker.lookupObject(AbstractRegistryBroker.java:130)
	at org.mule.registry.MuleRegistryHelper.lookupObject(MuleRegistryHelper.java:763)
    + 3 more (set debug level logging or '-Dmule.verbose.exceptions=true' for everything)
********************************************************************************

[INFO] instance 'a835a0b0-94f6-11e4-bffd-b82a72c92f56' of job 'batchProcessForConfCodes' has reached the max allowed number of failed records. Record will be added to failed list and the instance will be removed from execution pool

**Comment by damiansima** [comment]
Hi @reddikumar001 

this seems to look more like a batch thing than an Munit thing. 

Could you please clear all your application data from studio? 
Check out Run Configurations, General tab there is a choice for clearing application data.

Also, is the application running correctly, that is, with out Munit? 

Finally, the stack trace on it's own doesn't really say much.
Could you please share your project?

Cheers!!
