### ISSUE TITLE
Mule patch

### ISSUE THREAD

**Issue by sleone** [mulesoft/munit#151]
Hi guys,
I'm trying to write some munit tests, but they fail because there is a bug in mule.
The mulesoft support released a patch to fix it.

what's the best way to use the patch during the maven test phase with munit?

Thanks.

**Comment by damiansima** [comment]
Hi @sleone 

This looks more a question for mule core but any way...
What you may be able to do is to install the patch in your local .M2 repository, like so:

Maven Install the file in the local repository:
mvn install:install-file -Dfile={patch-file-name}.jar -DgroupId=com.mule.support -Dversion=1.0 -DartifactId={patch-name} -Dpackaging=jar

Reference the library (using the information supplied in the previous step) in your project's pom.xml making sure it is the first dependency in the list of dependencies.

Hope it works.
Cheers!!!
