### ISSUE TITLE
Munit Version,Issues and Sample Code

### ISSUE THREAD

**Issue by rajkumar79** [mulesoft/munit#152]
Whats the most stable version for MUnit.

We would like to use it for flows that call another using the below mentioned integration patters,

1.Mule Flow has Component Bindings that invoke a VM end point/
2.invoke http outbound endpoints.
invoke HTTPS calls. etc..

Are there any known issues that does not support this functionality.

**Comment by rajkumar79** [comment]
Has anyone implemented any complex Munit Which involves testing a mule applicaiton that involves a rest component, component bindings, http,https end points and JMS end points.

Would appreciate if anyone can come forward and share these learnings.

**Comment by damiansima** [comment]
Hi @rajkumar79 

Regarding your first question, currently the most stable version of Munit is 3.5-M3-SNAPSHOT. 
It has been proveen the most and has several bug fixes. 

Based on the description provided I see no problems that stop you from using Munit to do what you want to achieve.
