### ISSUE TITLE
3.6 Release Timeline

### ISSUE THREAD

**Issue by sohrab-** [mulesoft/munit#155]
Roughly how far away are we from a stable release for Mule 3.6 to be available in Mulesoft repo? It would be good if I can give my clients some idea as is it going to be weeks? months?

I am using the BETA-SNAPHSHOT at the moment. Personally not as fussed since it is used for testing only and not deployed to production.

**Comment by damiansima** [comment]
Hi @sohrab- 

There is yet not firm date, sorry about that. 
But I would say we are in the range of months rather than weeks.

Cheers!
