### ISSUE TITLE
What is the exact use of Using Spy Message Processor

### ISSUE THREAD

**Issue by utsavvishnoi** [mulesoft/munit#158]
Hi I have used MUnit Test Kit and curious to know about the working of Spy Message Processor. 

1. What is Spy Message Processor ?
2. When to use this ? 
3. Advantage of using this ?

**Comment by damiansima** [comment]
Hi @utsavvishnoi 

Please first check this link: https://github.com/mulesoft/munit/wiki/spy-message-processors

But in short the SPY MP allows you to run assertions over the payload and the message before it reaches the MP and after the MP is done processing.
Which is useful when you don't which to mock the MP but still run validations over the content of the message with which it will process.
