### ISSUE TITLE
Can we mock amqp and new database connector?

### ISSUE THREAD

**Issue by cchilukoori** [mulesoft/munit#160]
I am trying to write a unit test case for the below flow which has amqp and new database connector.
How do we nee mock these 2 connectors?

<flow name="franchiseEnrichment" doc:name="franchiseEnrichment">
		<logger message="PROCESS=FRANCHISE_ENRICHMENT, GUID=#[flowVars['guid']], FLOW=#[flow.name]" level="INFO" doc:name="Logger"/>
		<enricher target="#[flowVars['source']]" doc:name="Message Enricher">
			<db:select config-ref="Global_mysql" doc:name="Database">
		         <db:parameterized-query><![CDATA[SELECT guid, provider_id, n.name AS network_name, product_type,meta_id_from_partner, meta_title, meta_description, 
                    tv_rating, tv_advisories, star_rating, meta_showtype,  
                    meta_franchise_title, meta_episode_title, meta_episode_number, meta_season_number, actors, 
                    year, meta_tms_franchise_id,CONCAT(DATE_FORMAT(meta_airdate, '%a, %d %b %Y %H:%i:%S '), @@system_time_zone) AS meta_airdate
                    from source JOIN networks n ON network_id = n.id WHERE guid=#[flowVars['guid']];]]></db:parameterized-query>
		    </db:select>
	   	</enricher>
	   	
		<enricher target="#[flowVars['genres']]"  source="#[groovy:payload.genre]" doc:name="Message Enricher">
			<db:select config-ref="Global_mysql" doc:name="Database">
		         <db:parameterized-query><![CDATA[SELECT genre FROM genres WHERE source_guid=#[flowVars['guid']];]]></db:parameterized-query>
		    </db:select>
	   	</enricher>
	   	
	   	<enricher target="#[flowVars['categories']]" source="#[groovy:payload.category]" doc:name="Message Enricher">
			<db:select config-ref="Global_mysql" doc:name="Database">
		         <db:parameterized-query><![CDATA[SELECT category FROM categories WHERE source_guid=#[flowVars['guid']];]]></db:parameterized-query>
		    </db:select>
	   	</enricher>
	   	
	   	<enricher target="#[flowVars['offerings']]" doc:name="Message Enricher">
			<db:select config-ref="Global_mysql" doc:name="Database">
		         <db:parameterized-query><![CDATA[SELECT DATE_FORMAT(window_start, '%Y-%m-%dT%T') as window_start,  
		         DATE_FORMAT(window_end, '%Y-%m-%dT%T') as window_end, ruid, price, content_path, file_size, product_id, caid, naspid
		         FROM offerings WHERE source_guid=#[flowVars['guid']];]]></db:parameterized-query>
		    </db:select>
	   	</enricher>
	   	
	   	<expression-component doc:name="Expression"><![CDATA[              
               Map heimdalRequest = new HashMap();
               heimdalRequest.putAll(flowVars['source'][0]);
 
 			   Map categoriesMap = new HashMap();
               categoriesMap.put('category', flowVars['categories']);
               heimdalRequest.put('categories',categoriesMap);
               
               Map genresMap = new HashMap();
               genresMap.put('genre', flowVars['genres']);
               heimdalRequest.put('genres',genresMap);
               
               Map offeringMap = new HashMap();
               offeringMap.put('offering', flowVars['offerings']);
               heimdalRequest.put('offerings',offeringMap);
               
               heimdalRequest.put('created', new Date());
               payload = heimdalRequest; 
		]]></expression-component>
		<data-mapper:transform doc:name="heimdall-input" config-ref="heimdall-input"/> 
      	<enricher target="#[flowVars['requestXML']]" doc:name="Message Enricher">
      		<object-to-string-transformer doc:name="Object to String"/>
      	</enricher>
      	<logger message="PROCESS=FRANCHISE_ENRICHMENT, STEP=INPUT_REQUEST, GUID=#[flowVars['guid']], PAYLOAD=#[flowVars['requestXML']], FLOW=#[flow.name]" level="INFO" doc:name="Logger"/>
      	<amqp:outbound-endpoint responseTimeout="10000" doc:name="FarallonCategoryNotifyHydra" 
    	exchangeDurable="true" exchangeName="franchiseEnrichment" exchangeType="direct" routingKey="ToHeimdall"/>
		<db:update config-ref="Global_mysql" doc:name="Update enrich_status status as Posted">
              <db:parameterized-query><![CDATA[UPDATE source SET enrich_submitted=CURRENT_TIMESTAMP, enrich_completed=null, enrich_status='Posted' WHERE guid=#[flowVars['guid']];]]></db:parameterized-query>
        </db:update> 
        <flow-ref name="EnrichCategories" doc:name="Enrich Categories" />
        <exception-strategy ref="Global_Exception_Strategy" doc:name="Reference Exception Strategy"/>
	</flow>

**Comment by cchilukoori** [comment]
I tried to run the unit test from here: https://github.com/mulesoft/munit/blob/munit-3.5.x/munit-integration-tests/src/test/munit/db-connector-test.xml

but it is tyring to talk to the database. Why is that? We are mocking the db:select.  I am using AnyPoint studio October 2014 release.

Here is the error I got:

'org.mule.api.MessagingException: java.sql.SQLException: Cannot get connection for URL jdbc:mysql://localhost:3306/fake_db : Communications link failure

**Comment by cchilukoori** [comment]
Never mind. I saw that it will work with only January anypoint release and new munit. I will try with that.

**Comment by cchilukoori** [comment]
I am getting this error when running db_connector_test.xml :

Exception in thread "main" java.lang.RuntimeException: org.mule.api.config.ConfigurationException: Line 16 in XML document from URL [file:/Users/chaitanya/AnypointStudio/workspace/sample/target/classes/db_connector_test.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 16; columnNumber: 65; cvc-complex-type.4: Attribute 'config-ref' must appear on element 'mock:when'. (org.mule.api.lifecycle.InitialisationException)
	at org.mule.munit.runner.mule.MunitSuiteRunner.<init>(MunitSuiteRunner.java:47)
	at org.mule.munit.runner.mule.MunitSuiteRunner.<init>(MunitSuiteRunner.java:36)
	at org.mule.munit.runner.remote.MunitRemoteRunner.run(MunitRemoteRunner.java:40)
	at org.mule.munit.runner.remote.MunitRemoteRunner.main(MunitRemoteRunner.java:143)
Caused by: org.mule.api.config.ConfigurationException: Line 16 in XML document from URL [file:/Users/chaitanya/AnypointStudio/workspace/sample/target/classes/db_connector_test.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 16; columnNumber: 65; cvc-complex-type.4: Attribute 'config-ref' must appear on element 'mock:when'. (org.mule.api.lifecycle.InitialisationException)
	at org.mule.config.builders.AbstractConfigurationBuilder.configure(AbstractConfigurationBuilder.java:49)
	at org.mule.config.builders.AbstractResourceConfigurationBuilder.configure(AbstractResourceConfigurationBuilder.java:69)
	at org.mule.context.DefaultMuleContextFactory$1.configure(DefaultMuleContextFactory.java:84)

**Comment by damiansima** [comment]
Hi @cchilukoori 

So please let me address the topics in this thread.

First, the AMQP connector use as outbound endpoint.
Due to the way the connector is coded and a gap in the functionality of Munit you won't be able to successfully mock the AMQP connector. This is, you will be able to mock the connector call but on Test start you will still need a valid AMQP server up and running. I  know this is far from ideal but may be this understanding will let you continue your work while I fix this gap in Munit. 

Regarding the last question:
```
cvc-complex-type.4: Attribute 'config-ref' must appear on element 'mock:when'. 
```

I asume you're using munit version 3.6.0-BETA. 
If that so you need to have your mock configuration defined like:
```xml
<mock:config name="mock_config_name" doc:name="Mock configuration"/>
```
And then reference such mock configuration in all the MP of the mock namespace in your case the mock:when.

I'll be closing this thread if you find further problems testing the DB connector please open a new one
