### ISSUE TITLE
How to use Logger in MUnit

### ISSUE THREAD

**Issue by utsavvishnoi** [mulesoft/munit#161]
Hi I am working with MUnit and i am not able to  use Logger component with MUnit . Please help me to use Logger with MUnit Test cases.

![navh](https://cloud.githubusercontent.com/assets/4372935/6387702/962663ea-bdb5-11e4-8d8c-47611f192e06.png)

**Comment by damiansima** [comment]
Hi @utsavvishnoi,

If you're using Mule ESB 3.5.x that uses Log4j then you just need to throw a log4j.properties in the classpath. Something like this will do 
```
# Default log level
log4j.rootCategory=WARN, console

log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%-5p %d [%t] %c: %m%n

################################################
# You can set custom log levels per-package here
################################################

# CXF is used heavily by Mule for web services
#log4j.logger.org.apache.cxf=ERROR
log4j.logger.org.apache.cxf=WARN

# Apache Commons tend to make a lot of noise which can clutter the log.
#log4j.logger.org.apache=ERROR
log4j.logger.org.apache=WARN

# Reduce startup noise
log4j.logger.org.springframework.beans.factory=WARN

# Mule classes
log4j.logger.org.mule=INFO
log4j.logger.com.mulesoft=INFO

# Reduce DM verbosity
log4j.logger.org.jetel=WARN
log4j.logger.Tracking=WARN


# Mule Loggers
log4j.logger.org.mule.api.processor.LoggerMessageProcessor=DEBUG
```

Please notice the last line is the one for the logger message processor.

If you are using Mule ESB 3.6.x, I just discover an small issue there. There is no easy(or nice ) way to do so. Once the guys in the ESB solve the problem I'll document both ways in the wiki.

Cheers
