### ISSUE TITLE
Spy is not Working in MUnit

### ISSUE THREAD

**Issue by utsavvishnoi** [mulesoft/munit#162]
Hi I am working with MUnit and i am not able to get the desired output using SPY and MOCK . Please check the XML and let me know how to use this. 

Below is the Link to get the code : 
http://pastebin.com/Vk4sxt7T

**Comment by damiansima** [comment]
Hi there, 

For starters you're not telling the SPY  what MP to actually spy. 
It should have at least an attribute like: messageProcessor=".*:.*" 
If you choose to say that to spy you should then provide and attribute to match: 
```xml
<mock:with-attributes>
     <mock:with-attribute whereValue-ref="#['the value of the attribute']" name="the_name_of_the_attribute"/>
</mock:with-attributes>
```

Please take a look at these wiki page: https://github.com/mulesoft/munit/wiki/spy-message-processors
