### ISSUE TITLE
Is sub-flow testing now supported in Java for later versions of MUnit?

### ISSUE THREAD

**Issue by jcbusta** [mulesoft/munit#165]
I know that in the following thread, https://github.com/mulesoft/munit/issues/45, that java didn't support sub-flow testing. That thread was made over 2 years ago, and in version 3.4 of munit. Does that still hold true for the latest versions of MUnit? 

Thanks in advance,

Juan

**Comment by damiansima** [comment]
Hi @jcbusta 

Yes you can certainly test (run) a sub-flow from a Munit java based test.
Here is an example:
**Production Code**
```xml
    <sub-flow name="github-165Sub_Flow">
        <set-payload value="#['lalero']" doc:name="Set Payload"/>
    </sub-flow>
```
**Test Code**
```java
public class TheTest extends FunctionalMunitSuite {

    @Override
    protected String getConfigResources() {
	return "github-165.xml";
    }

    @Test
    public void test() throws MuleException, Exception {
	MuleEvent responseEvent = runFlow("github-165Sub_Flow", testEvent(""));
	Assert.assertEquals("The payload is wrong", "lalero", responseEvent.getMessage().getPayload());

    }
}
```

Not sure when we add this feature but it's there since 3.5-M3-SNAPSHOT
