### ISSUE TITLE
Not able to run munit from AnyPoint studio

### ISSUE THREAD

**Issue by cchilukoori** [mulesoft/munit#172]
I have installed Any Point Studio 2015 January release and MUnit 3.6. 

I added munit test case to a existing file which is a maven project. When I try to run munit from studio (without maven), it give me this error: In the build path, I don't see Munit 3.6. How do I add it there?

Error: Could not find or load main class org.mule.munit.runner.remote.MunitRemoteRunner

I created another simple project which is not Maven and added a test case. It automatically added mUnit to the build path and I am able to run the test case. 

Please help.

**Comment by damiansima** [comment]
Hi @cchilukoori 

This is a but on the Munit Studio plugin that has already been solved but not released.
This solution is a hack and hopefully you won't have to do this in the near future but just to get you up and running. 
Please verify that you have the following lines in your .classpath file:
```xml
<classpathentry exported="true" kind="con" path="MUNIT_RUNTIME"/>
<classpathentry kind="src" path="src/test/munit"/>
```

Cheers

**Comment by cchilukoori** [comment]
Yes I have them in my .classpath file.

Here is my file:


<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry exported="true" kind="con" path="MULE_RUNTIME"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
	<classpathentry kind="src" path="src/main/java"/>
	<classpathentry kind="src" path="src/test/munit"/>
	<classpathentry kind="src" path="src/test/java"/>
	<classpathentry kind="src" path="src/main/resources"/>
	<classpathentry kind="src" path="src/test/resources"/>
	<classpathentry kind="lib" path="/Users/chaitanya/farallon/lib/amqp-client-3.2.1.jar"/>
	<classpathentry kind="lib" path="/Users/chaitanya/farallon/lib/groovy-xmlrpc-0.8.jar"/>
	<classpathentry kind="lib" path="/Users/chaitanya/farallon/lib/mule-transport-amqp-3.4.3.jar"/>
	<classpathentry kind="lib" path="/Users/chaitanya/farallon/lib/mysql-connector-java-5.1.21-bin.jar"/>
	<classpathentry kind="src" path="src/main/app"/>
	<classpathentry kind="src" path="mappings"/>
	<classpathentry kind="output" path="bin"/>
</classpath>

**Comment by damiansima** [comment]
Hey sorry for the delay.

So you say you have those line in your classpath, but do you have it in the first or in the second project?

In any case could you please send me the classpath of the failing project (the project as a whole will be better though).

But as I said this is a bug in the Munit studio plugin and it's been fixed already, I just want to validate there is nothing else hidden there ;)

**Comment by cchilukoori** [comment]
Yes I have both of them on the project that is having issues. After adding the below line, it started working. Now I am able to run the test cases.

<classpathentry kind="con" path="MUNIT_RUNTIME"/>
