### ISSUE TITLE
How to mock message inbound property

### ISSUE THREAD

**Issue by cchilukoori** [mulesoft/munit#174]
Hi,

How can I mock message inbound property. Here is my flow:

<flow name="_ingest_clearleap" doc:name="Ingest Clearleap" processingStrategy="synchronous">
        <file:inbound-endpoint path="${farallon.path.partner.watch.clearleap}" moveToDirectory="${farallon.path.metadata.working}" pollingFrequency="${farallon.rsc.watchFolderMonitorFrequency}" fileAge="${farallon.rsc.minFileAge}" responseTimeout="${farallon.rsc.responseTimeout}" doc:name="XML Watch">
            <file:filename-regex-filter pattern=".*\.XML$" caseSensitive="false"/>
        </file:inbound-endpoint>
		<file:file-to-string-transformer/>
		<set-variable variableName="partnerID" value="132" doc:name="Set Partner ID" doc:description="REQUIRED. HARDCODED BASED ON partners TABLE ENTRY."/>
        <set-variable variableName="xmlContent" value="#[payload:]"/> 
        
		<set-variable variableName="metadataFilename" value="#[message.inboundProperties['originalFilename']]" doc:name="Get Metadata Filename" doc:description="REQUIRED. NO NEED TO CHANGE THIS. THIS ALWAYS HOLDS THE VALUE OF THE METADATA FILENAME."/>
		<logger message="PROCESS = INGEST, #[payload], FLOW = #[flow.name]" level="INFO" doc:name="Logger"/>   
		<set-variable variableName="networkName" value="#[XPATHEval://AMS[@Asset_Class='movie']/@Provider]" doc:name="Get Network Name" doc:description="REQUIRED. THIS VALUE EITHER NEEDS TO COME FROM THE XML OR BE HARDCODED TO A VALUE THAT MATCHES A DEFINED NETWORK NAME IN THE DB."/>

I want to mock metadataFilename and return a value in the test case.

Here is my test case:

<munit:test name="testGoodXML" description="Test good XML">
    	<munit:set payload-ref="#[getResource('ClearLeap_Good.xml').asString()]" doc:name="Set Message"/>

    	<mock:when config-ref="mock_ingest_clearleap" messageProcessor="flow">
            <mock:with-attributes>
                <mock:with-attribute name="name" whereValue-ref="#['GlobalIngestRouter']"/>
            </mock:with-attributes>
        </mock:when>
    	
    	<flow-ref name="_ingest_clearleap" doc:name="Flow Reference"/>
    	
    	<mock:verify-call config-ref="mock_ingest_clearleap" messageProcessor="flow" times="1">
    		<mock:attributes>
                <mock:attribute name="name" whereValue-ref="#['GlobalIngestRouter']"/>
            </mock:attributes>
        </mock:verify-call>
    	
    	<munit:assert-on-equals message="SourceVideoFileName Assertion Failure" expected-ref="#['XTRA_Musketeers_1_03_SD.mpg']" value-ref="#[flowVars['sourceVideoFilename']]"/>
    	<munit:assert-on-equals message="metaIdFromPartner Assertion Failure" expected-ref="#['BBCA0002005410035001']" value-ref="#[flowVars['metaIdFromPartner']]"/>
    	<munit:assert-on-equals message="metaYear Assertion Failure" expected-ref="#['2014']" value-ref="#[flowVars['metaYear']]"/> 
		<munit:assert-on-equals message="ingestPath Assertion Failure" expected-ref="#['/mnt/farallon/_partners/_iptv/']" value-ref="#[flowVars['ingestPath']]"/>
		<munit:assert-on-equals message="metadata file name Assertion Failure" expected-ref="#['ClearLeap_Good.xml']" value-ref="#[flowVars['metadataFilename']]"/>
    	
		
    </munit:test>

**Comment by cchilukoori** [comment]
I got it working by using munit:inbound-property on payload.

**Comment by damiansima** [comment]
Great !
