### ISSUE TITLE
Testing flow with http inbound endpoint

### ISSUE THREAD

**Issue by abhusari** [mulesoft/munit#182]
I am trying to write munit test for flow which has http inbound endpoint, I haven,t found anything related to  inbound endpoint. I am testing following simple flow. This is not the intented flow but basic issue is with the http inbound endpoint. Please suggest me how to work with it. 
![untitled](https://cloud.githubusercontent.com/assets/3222631/7413618/ee213f5c-ef6a-11e4-91d7-b4f5f9225697.jpg)

**Comment by damiansima** [comment]
Hi @abhusari, 

Could you please be a little bit more specific? 

Are you trying to hit the http inbound endpoint from your MUnit test or just trigger the flow regardless the way?

In the first case you can just use an http outbound endpoint (or http request depending on the mule version). 

If not you will be just as well with a flow ref. 

That said, if you chose the first option bear in main that by default MUnit disable inbound endpoints. You can change this behaviour from the munit:config.

Cheers!!

**Comment by abhusari** [comment]
Hi,
Thanks for the help. Flow reference worked for me. Just added the set payload before flow reference.
