### ISSUE TITLE
Testing mule ee features with munit and maven

### ISSUE THREAD

**Issue by ajung** [mulesoft/munit#183]
Hi

i want to test ee features with munit but i get the exception:
java.lang.RuntimeException: Invalid license
I am a ee customer and have a licene file located here:
src/test/resources/muleLicenseKey.lic

**Comment by damiansima** [comment]
Hi @ajung ,

Please make suer that src/test/resources is part of the classpath
```
<testResources>
  <testResource>
    <directory>src/test/resources</directory>
  </testResource>
</testResources>
```

Cheers!

**Comment by ajung** [comment]
Hi @damiansima 
thank you for the response, but i have the src/test/resources in my classpath and it is still not working.

**Comment by damiansima** [comment]
Well if you have everything in place, the other thing I can think of is the lic file.

You see the license  checking is not actually MUnit is rather Mule building from maven, as long as the correct lic file is in the classpath you should be ok so the only other thing may be the lic file. 

Just to be sure try placing the file in src/main/app (just for testing) if that still doesn't work please check you lic file. Bear in mind it should be the same file that's installed in your MULE installation folder (the one processed by mule).

Cheers!

**Comment by ajung** [comment]
Hi

i try to place the lic file in src/main/app, and it still not working. I can build my project with maven and run it on a enterprise mule. 
I think that munit start a mule server inside the maven run. In this starting process, there yould be a point where the licence should be installed. 
In my production enviroment i call  -installLicense on mule.

**Comment by jon-elliott** [comment]
I had this problem - have you validated your licence ? If so you licence file will be called muleLicenceKey.lic - if you put this is src/main/resources it should all be loverly jubberly and work a treat.

**Comment by ajung** [comment]
So i just solve the problem. There are two version of lic files. The original mule-ee-licence.lic and the muleLicenceKey.lic which is a xml file. I have to use the xml file.
