### ISSUE TITLE
Skipping th Munit test at the time of maven build

### ISSUE THREAD

**Issue by abhusari** [mulesoft/munit#184]
Hi,

I am having both Junit and Munit testcases. Is there any way to skip Munit test cases only. I have tried "mvn clean package -DskipTests", but it skips both Junit and Munit testcases.

**Comment by damiansima** [comment]
Hi @abhusari, 

MUnit maven plugin hocks to the same property that the one offered by maven that is -DskipTests.
So if you add that to your command line it will always skip both, there is no way to skip one but not the other from the command line.

Another thing that may help you though is to ignore each MUnit test. I know it's a pain but at least it'll get you going. 

Cheers!

**Comment by abhusari** [comment]
Thanks
