### ISSUE TITLE
Munit attempting to update POM file even though Anypoint option to manage POM is disabled

### ISSUE THREAD

**Issue by davemcgowan** [mulesoft/munit#193]
after installing Munit, my POM file was not working, so I disabled the automatic POM managemet, reset and added the dependancies and plugins manually.  

However - I'm still seeing the following message. It sometimes happens when I make changes to the POM file, but I've also seen it when running the mule app.

> An internal error occurred during: "configure_project_for_munit".
> Trying to write pom.xml file while in an invalid state[/cpde]

**Comment by damiansima** [comment]
Hi @davemcgowan, 

We are aware of this issue. I'm sorry about that :(

The problem is in our Mule Studio plugin, and we have already taking care of it. You shouldn't see that on the future.  Thanks for reporting it .
Cheers, Damian.

**Comment by nikolaiblackie** [comment]
Can you confirm the date when this fix is scheduled for release? We can't run our MUnit tests in CI because of it.

**Comment by karlignatius** [comment]
I see that a new branch was created 3 days ago. Would this branch contain the fix mentioned above?

**Comment by damiansima** [comment]
Hi guys, 

I understand the frustration.
The source of this issue lies not in MUnit core source code, but in the MUnit Studio Plugin. 
A release of that is schedule to be out in a few weeks. 

Please be patient
Cheers!
