### ISSUE TITLE
How to set properties to a message?

### ISSUE THREAD

**Issue by lorochka** [mulesoft/munit#51]
Hey, guys!

I need my message not only have payload, but some properties too. 

How to do it?

Thanks,
Laura.

**Comment by damiansima** [comment]
Hi @lorochka 

I realise that this is old but, in the last test I did Mule studio shows no schema error when using set-variable or set-property in a Munit test.

Also you can achieve the same result by doing 

```xml
<munit:set payload-ref="#[]" doc:name="Set Message">
            <munit:invocation-properties>
                <munit:invocation-property key="routingKey" value-ref="#['value']"/>
            </munit:invocation-properties>
            <munit:outbound-properties>
                <munit:outbound-property key="MULE_ENDPOINT" value-ref="#['value']"/>
            </munit:outbound-properties>
</munit:set>
```

Could you please double check it in a newer version of Studio?
If it keeps happening please reopen this bug.

Cheers!!
